### ISSUE TITLE
Button on the card

### ISSUE THREAD

**Issue by manideep-1** [coderplex/learnplex#155]
**Describe the bug**
When the button "coderplex" is clicked then one of the cards are hiding.

**To Reproduce**
1. Go to https://coderplex.in/
2. Click on coderplex on 4th card
![image](https://user-images.githubusercontent.com/41748609/83361690-905bf400-a3a8-11ea-8446-460243b93726.png)
3. See error
![image](https://user-images.githubusercontent.com/41748609/83361702-abc6ff00-a3a8-11ea-941d-e6aeb926b9a8.png)

**Desktop :**
 - OS:Windows
 - Browser : chrome

**Comment by pbteja1998** [comment]
It's expected behaviour. One of the cards is not hiding. If you see the two images, the urls are different for both. When you click on `coderplex` tag, it is going to a page which shows all the resources created by `coderplex`. `React Lifecycle Methods` is not created by `coderplex` account. Hence it is not being showed there.
